name: "trykar-filebeat"
logging.metrics.enabled: false
xpack.security.enabled: false
xpack.monitoring.enabled: false
setup.ilm.enabled: false
setup.template.enabled: false
setup.template.name: "filebeat"
setup.template.pattern: "filebeat"
setup.kibana.host: kibana:5601

filebeat.inputs:
- type: log
  scan_frequency: 1s
  enabled: true
  paths: /server/logs/*.log
  fields:
    - service: server
  fields_under_root: true
  parsers:
    - ndjson:
      overwrite_keys: true 
      add_error_key: true 
      expand_keys: true 


output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "server"
