services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.name=elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data-volume:/usr/share/elasticsearch/data
    networks:
      - elk

  # logstash:
  #   image: docker.elastic.co/logstash/logstash:8.13.4
  #   container_name: logstash
  #   ports:
  #     - "5044:5044"
  #   volumes:
  #     - ./logstash-pipeline:/usr/share/logstash/pipeline

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    restart: always
    container_name: kibana
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk

volumes: 
  elasticsearch-data-volume:
    driver: local

networks:
  elk: