---
- name: Deploy Application
  hosts: all
  remote_user: jay
  become: true

  tasks:
    - name: Pull server image
      docker_image:
        name: "jaypanchal14/trykar-server"
        source: pull

    - name: Pull signal-server image
      docker_image:
        name: "jaypanchal14/trykar-signaling-server"
        source: pull

    - name: Pull client image
      docker_image:
        name: "jaypanchal14/trykar-client"
        source: pull

    - name: Copy Docker Compose file to host
      copy:
        src: /var/lib/jenkins/workspace/TryKar/docker-compose.yml
        dest: /opt/docker-compose.yml

    - name: Run containers using docker-compose
      command: docker-compose up -d
      args:
        chdir: /opt/